name: "Testing with nixos environment"

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install Nix
      uses: cachix/install-nix-action@v26
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Build Project
      run: nix build

    - name: Check Project
      run: nix flake check
    
    - name: Test Project
      run: nix develop --command bash -c "poetry install && poetry run pytest ."